#system("git checkout gh-pages")
rmarkdown::render("index.Rmd")
#system("phantomjs /usr/local/decktape-1.0.0/decktape.js index.html index.pdf")
system("decktape remark index.html lakes_landsacpe_r.pdf")
system("git add -A; git commit -m 'fresh render index'")
system("git push origin master")